### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ghost** [iam-py-test/allowlist#1]
Please add
```
xhwide2.com
xhwide3.com
xhwide4.com
xhwide5.com
xhwide6.com
xhwide7.com
```

**Comment by ghost** [comment]
Also `shortcut.agency` should be removed

**Comment by iam-py-test** [comment]
> Also `shortcut.agency` should be removed

Removed. I will look at those other ones later today
Thank you

**Comment by iam-py-test** [comment]
Out of curiosity, where did you find these?

**Comment by iam-py-test** [comment]
Added, thanks

**Comment by ghost** [comment]
`xhamster.com` used to redirect to these domains
